"""
Docstring for constants.app
"""

from features.appdata import *

# REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR
# แบ่งหมวดหมู่ของ Constants แต่ละหมวด เช่น APP -> (APP.PATH, APP.NAME), REF
# REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR REFACTOR

APP_NAME = ''
APP_PATH = ''
APP_SIZE = ''
APP_VERSION = ''

APPDATA_PATH = ''
APPDATA_SIZE = ''

KEY_CRYPTION = ''